### ISSUE TITLE
Replace trait-implementing objects with classes

### ISSUE THREAD

**Issue by beatngu13** [retest/gui-state-machine-api#12]
For instance, `GuiStateMachineApi` and its implementation look as follows:

```scala
trait GuiStateMachineApi { /* ... */ }

object GuiStateMachineApiImpl extends GuiStateMachineApi { /* ... */ }
```

Is this a thing in Scala to let objects implement traits? In Java, it looks a bit odd since I cannot code against the actual API anymore. Instead, I have to use the implementation directly:

```java
Id stateMachineId = GuiStateMachineApiImpl.createStateMachine();
// ...
```

**Comment by tdauth** [comment]
Done. See https://github.com/retest/gui-state-machine-api/commit/cc012454225d53c937ef0bc494821f4281427856
