### ISSUE TITLE
Use Neo4J backend

### ISSUE THREAD

**Issue by tdauth** [retest/gui-state-machine-api#19]
See #5 for the investigation of GraphDBs.

Neo4J allows transactions which provide concurrency support.
It can also visualize the state machines/graphs.

Labels group nodes together, so a SutState is not really a label.
An action type can be a label.

Some information about OGM:
- https://neo4j.com/docs/ogm-manual/current/tutorial/#tutorial:introduction
- https://github.com/neo4j-examples/neo4j-ogm-university

We store only the hashes and some additional information of the SutStates and actions in the graphdb.
Otherwise, it would be an antipattern.
Note that we need to use the Bolt protocol to utilize most of the tools for visualization and management.
Embedded databases are useful for storage only.

Open questions:

* How can we separate graphs with Bolt? Different port numbers?
* How does the user specify username and password for one graph database using the API?
* Does the user have to setup a Bolt Neo4J database before he/she can use the API or does our API automatically set it up for the first time?
* Which tools are the best for management and visualization? I have found the Desktop application https://neo4j.com/developer/neo4j-desktop/ which allows you to start Bolt graph databases and brings a browser which can visualize them. The browser's UI is available in a web browser as well. There are import/export apoc procedures which can be installed for GraphML etc.: http://neo4j-contrib.github.io/neo4j-apoc-procedures/3.5/export-import/graphml/

**Comment by beatngu13** [comment]
The question is also: Do we drop the in-memory representation of the SUT model as soon as we have the DB backend?

**Comment by beatngu13** [comment]
Regarding the node content, [BLOBs seem to be an anti-pattern](https://neo4j.com/blog/dark-side-neo4j-worst-practices/):

>If you have to deal with BLOB data, choose an appropriate store for that use case and use Neo4j to store the URL that points you to the binary data.

This is also what @martin-v suggested, to only reference the state in Neo4j and store the actual data somewhere else, e.g., a key-value store.

The question is: How can we deterministically derive a unique ID from the state data that can be used as a reference. This also heavily depends on the upcoming artifact storage.

For now, we decided to go with a filtered textual representation of the state in Neo4j.

**Comment by tdauth** [comment]
We have to use Scala 2.11.x https://github.com/neo4j/neo4j/issues/8832

**Comment by beatngu13** [comment]
Side note: Neo4j is [licensed under GPLv3](https://github.com/neo4j/neo4j#licensing). So if we use Neo4j, we have to check what surili components need a compatible license.

**Comment by beatngu13** [comment]
From https://neo4j.com/licensing/:

>We chose GPL [v3] because it means that Neo4j Community Edition can be used for free with your project: whether in the cloud or behind the firewall. If you’re building an application that accesses a Neo4j database running inside your organization (or on any personal device), then **you are free to use Community Edition, whether or not your software is closed source**.

Sounds good, but the questions is also does the CE include everything we need?

**Comment by tdauth** [comment]
https://neo4j.com/subscriptions/#editions

**Comment by tdauth** [comment]
Documented advantages vs disadvantages. Simple database like PostgreSQL or SQLite would be sufficient. If we really need advanced features from Neo4J, we can still use it in the future.
