### ISSUE TITLE
Get action that lead to one state.

### ISSUE THREAD

**Issue by PickHub** [retest/gui-state-machine-api#24]
It would be really useful to have a helper method in the GuiStateMachine that returns all actions that lead to one SutState, instead of only the `getAllExploredActions` method. Something like: `getIncomingActions(SutState state)`.

**Comment by beatngu13** [comment]
Or should `State` offer something like `to()` and `from()` / `ingoing()` and `outgoing()` / … to retrieve lists of actions?

**Comment by PickHub** [comment]
True, that would be better in terms of computation.

**Comment by beatngu13** [comment]
Resolved via #25.
