### ISSUE TITLE
Ignore retestId when generating checksum from serializables SutState and Action

### ISSUE THREAD

**Issue by tdauth** [retest/gui-state-machine-api#33]
Apparently the field `Element.retestId` is generated with random values and is not the same every time. We have to filter it when generating the hash value or make sure that Surili does always generate the same value.

**Comment by beatngu13** [comment]
I recently created this PR on Bitbucket:

https://bitbucket.org/retest/surili/pull-requests/38/

I thought about this twice and I'm unsure if this isn't something we should "simply" do on the SUT model-side. That is, when we create the hash, we should ignore it.

What do you think?

**Comment by tdauth** [comment]
> when

We can do this if there is a way to exclude the field for serialization. I have only found transient.
Alternatives are to create a custom byte stream with all data except the retestId, to copy the whole SutState except the retestId in a new SutState or to create a custom state class for the monkey.

**Comment by tdauth** [comment]
Surili uses a FakeRetestIdProvider. Hence, the retestId will always be the same.
