### ISSUE TITLE
Provide simple Scala API

### ISSUE THREAD

**Issue by tdauth** [retest/gui-state-machine-api#4]
A REST API might be too slow when the state machine is updated constantly.
Hence, provide a simple Scala API which can be called directly in Java.

**Comment by beatngu13** [comment]
>[…] Scala API which can be called directly in Java.

We still go over network, don't we? This sounds like RPC… 🙈

**Comment by tdauth** [comment]
> > […] Scala API which can be called directly in Java.
> 
> We still go over network, don't we? This sounds like RPC… see_no_evil

This API should not be called via network. It would have to be used as direct maven/sbt dependency of the service which creates the state machine.

**Comment by tdauth** [comment]
Done, open more issues for specific features.
